Build during pre-commit hook
- Validate build
- Keep local build files up to date

diff --git a/git-hooks/pre-commit b/git-hooks/pre-commit
--- a/git-hooks/pre-commit
+++ b/git-hooks/pre-commit
@@ -53,6 +53,20 @@ function validate_ts() {
 }
 validate_ts &
 
+function build() {
+    echo "${YELLOW}[pre-commit]${BLUE} Running \`yarn build\`... ${WHITE}"
+
+    OUTPUT=$(yarn build 2>&1)
+     if [[ $? != 0 ]]; then
+        echo
+        echo "${BLUE}Build failed."
+        echo "${RED}$OUTPUT"
+        exit_reset_colors
+    fi
+    echo "${YELLOW}[pre-commit]${GREEN} Build Completed!${WHITE}"
+}
+build &
+
 function js_lint() {
     echo "${YELLOW}[pre-commit]${BLUE} Running JS Lint... ${WHITE}"
     OUTPUT=$(yarn lipemat-js-boilerplate lint --fix=false 2>&1)
@@ -66,6 +80,7 @@ function js_lint() {
 
 }
 js_lint &
+
 
 
 # Go through each background task
